Repository hwsc-org/hwsc-document-svc, pull requests merged in 2018-12, with the labels that each got.

#12 Add Dockerfile
  Dockerfile
Labels: enhancement

#13 Add issue templates
  .github/ISSUE_TEMPLATE/bug--description-.md
  .github/ISSUE_TEMPLATE/epic--description-.md
  .github/ISSUE_TEMPLATE/feature--description-.md
  .github/ISSUE_TEMPLATE/test--description-.md
Labels: enhancement

#14 Fix dependencies after migration.
  Gopkg.lock
  Gopkg.toml
  main.go
  service/service.go
  service/service_test.go
  service/utility.go
  service/utility_test.go
Labels: enhancement

#15 Replace namespace
  Dockerfile
  README.md
Labels: enhancement

#25 Fix regex for file type
  service/utility.go
  service/utility_test.go
Labels: bug

#26 Configure docker yml for Azure
  azure-pipelines.yml
Labels: enhancement

#30 Separate stages
  azure-pipelines.yml
Labels: dev-deployment

#31 Update azure-pipelines.yml
  azure-pipelines.yml
Labels: dev-deployment

#34 Bug/revert
  main.go
  service/service.go
Labels: bug

#35 Add docker script
  README.md
  generate_container.sh
Labels: enhancement

#38 Fix nil bug in refreshMongoDBConnection
  service/db.go
Labels: bug

#40 Fix mongodb startup connection verification
  service/db.go
  service/db_test.go
Labels: bug

#41 bug/refresh-connection-mongodb
  service/db.go
  service/db_test.go
  service/error.go
  service/service.go
Labels: bug

#43 Remove storage retrieval validation
  azure-pipelines.yml
  service/service.go
  service/service_test.go
  service/unit_test.sh
  service/utility.go
Labels: enhancement
